# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ContactBook' do
	pod 'Masonry'

  target 'ContactBookTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
